steps:
  - name: golang
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t',
            'gcr.io/eco-lane-378504/github.com/robifirmnsyah/text-to-speech:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eco-lane-378504/github.com/robifirmnsyah/text-to-speech:$SHORT_SHA']
